name: remix_icons
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/Arkanum-Corporation/remix_icons_flutter_pub_package

environment:
  sdk: ">=2.19.6 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

flutter:
  fonts:
    - family: RemixIcons
      fonts:
        - asset: fonts/RemixIcons.ttf
dependencies:
  flutter:
    sdk: flutter
