name: remix_icons
description: Awesome Remix Icons available in Flutter
version: 1.0.0
homepage: https://github.com/Arkanum-Corporation/remix_icons_flutter_pub_package

environment:
  sdk: ">=2.19.6 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

flutter:
  fonts:
    - family: RemixIcons
      fonts:
        - asset: fonts/RemixIcons.ttf
